Updated Dockerfile.lite
GiriB/dependabot-core pull request #213
Opened 2021-04-14 06:43 UTC by milind009

Updated dockerfile.lite to keep it in sync with recent merge from dependabot-core main branch. For installing npm and yarn, the setup script i.e `https://deb.nodesource.com/setup_14.x` takes care of both. [Reference: https://github.com/nodesource/distributions/blob/master/deb/setup_14.x]

2021-04-14 07:05 UTC, GiriB requested changes

2021-04-14 07:05 UTC, GiriB commented on Dockerfile.lite
> +RUN bash /opt/npm_and_yarn/helpers/build /opt/npm_and_yarn
This just differs in newline?

2021-04-14 09:10 UTC, milind009 commented on Dockerfile.lite
> +RUN bash /opt/npm_and_yarn/helpers/build /opt/npm_and_yarn
Yes

2021-04-16 05:54 UTC, milind009 commented on Dockerfile.lite
> +RUN bash /opt/npm_and_yarn/helpers/build /opt/npm_and_yarn
Removed the extra newline at the end of file

2021-04-16 06:09 UTC, GiriB approved these changes

2021-04-16 07:01 UTC, merged