Handle .tar path dependencies
GiriB/dependabot-core pull request #371
Opened 2021-09-17 10:36 UTC by AlekhyaYalla

if a .tar extension file is given as path dependency in dependency files, dependabot failing to parse/handle. Handled the same tgz files are handled

2021-09-20 06:42 UTC, milind009 commented on npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
> +          filename = File.join(filename, "package.json") unless filename.end_with?(".tgz") or filename.end_with?(".tar")
nit: you can add the check for all supported extensions in the same `end_with?` function call as comma separated values like filename.end_with?(".tgz", ".tar") or using an array of supported extensions. Here is the documentation for the end_with? API: https://apidock.com/ruby/v2_5_5/String/end_with%3F

2021-09-20 06:42 UTC, milind009 commented on npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
> +          filename = File.join(filename, "package.json") unless filename.end_with?(".tgz") or filename.end_with?(".tar")
Are there any other extensions that are possible for path dependencies? Its good to add those here as well if it makes sense

2021-09-20 06:42 UTC, milind009 commented on npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
> +    context "with a tar path dependency" do
nit: Can we merge the tests for path dependencies having these extensions like .tar, .tgz,etc. and could proabably name it as `for non package.json path dependencies`. The reason being that i see a lot of repeated code in the `before` block and the actual tests with only changes in the file names for the .tar path dependency tests and .tgz dependency + if we want to add support for some other extension we just need add the stub files related to that extension for testing(unless the existing workflow needs to be changed for that extension)

2021-09-20 09:43 UTC, AlekhyaYalla commented on npm_and_yarn/lib/dependabot/npm_and_yarn/file_fetcher.rb
> +          filename = File.join(filename, "package.json") unless filename.end_with?(".tgz") or filename.end_with?(".tar")
So far with all the examples on the web, I see .tgz is most commonly given for path dependency. In our case, we observed .tar file as well. (Note: .tgz is the zipped tar file. )

2021-09-20 09:44 UTC, AlekhyaYalla commented on npm_and_yarn/spec/dependabot/npm_and_yarn/file_fetcher_spec.rb
> +    context "with a tar path dependency" do
Yes makes sense. Will be merging the common part. Most of the stubs actually making a little difference, so just kept them separate.

2021-10-05 12:55 UTC, GiriB requested changes
If we raised a PR on dependabot-core then let's close this PR.

2021-11-02 08:46 UTC, AlekhyaYalla commented
The change has been merged into upstream

2021-11-02 08:46 UTC, closed without merging